import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, PT_Mono, Palette_Mosaic} from "next/font/google";
import Link from "next/link";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // IMPORT THE INTER FONT
// const inter = Inter({
//   subsets: ["cyrillic"],
// })

// const pt_mono = PT_Mono({
//   subsets: ["cyrillic"],
//   weight: "400",
// })

const palette_mosaic = Palette_Mosaic({
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function NavBar() {
  return (
    <div className="flex flex-row justify-center items-center gap-4">
      <Link href={"/button_demo"} className="hover:text-red-600">Button Demo</Link> 
      <Link href={"/card_demo"} className="hover:text-red-600">Card Demo</Link>
    </div>
  )
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={` ${palette_mosaic.className} h-full antialiased`}
    >
      <NavBar />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
