import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, PT_Mono, Palette_Mosaic, Manrope} from "next/font/google";
import Link from "next/link";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// function NavBar() {
//   return (
//     <div className="flex flex-row justify-center items-center gap-4">
//       <Link href={"/button_demo"} className="hover:text-red-600">Button Demo</Link> 
//       <Link href={"/card_demo"} className="hover:text-red-600">Card Demo</Link>
//     </div>
//   )
// }

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${manrope.className} h-full antialiased`}>
      {/* <NavBar /> */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
